config/routes.rb
Users::Application.routes.draw do
  get "users/index"

     resources :users

   root :to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :age, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
      if @user.save
         redirect_to users_path
      else 
         render :new
      end
  end
  def show
    @user = User.find(params[:id])
  end
  def edit
    
    
        @param1= params["param1"]
        @user = User.find(params[:id])
        
  end
  def update
   # render :json => params
   # return
    param=params["param1"]   

    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      if(param=="show")  
          redirect_to user_path(@user)
      else           
          redirect_to users_path
      end
    else  
        render :edit
    end    
  end  
  def destroy
   @user=User.find(params[:id])
      if @user.destroy
         redirect_to users_path
      else 
         render :new  
      end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Users</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%=form_for(@user) do |f|%>
<%=hidden_field_tag :param1 , @param1%>
Name:<%=f.text_field :name%>
Age: <%=f.text_field :age%>
<%=f.submit%>
<%end%>

app/views/users/edit.html.erb
<%= render 'form'%>

app/views/users/index.html.erb
<h1>Welcome Users</h1>


<table>
  <tr>  
    <th>Name</th>
    <th>Address</th>
    <th>Action</th>
  </tr>
<% @users.each do |u|%>
  <tr>
    <td><%=u.name %></td>
    <td><%=u.age%></td>
    <td><%=link_to :edit,  edit_user_path(u)%>&nbsp<%=link_to :show , user_path(u) %>&nbsp<%=link_to :destroy,user_path(u), :method => :delete, :confirm => "Are you sure"  %></td>
  </tr>
<%end%>
</table>
<%=link_to :add_user,new_user_path %>

app/views/users/new.html.erb
<h1>Welcome Users</h1>
<%=render 'form'%>

app/views/users/show.html.erb
<h1>Welcome User</h1>
<table>
   <tr>
     <td>User Name</td><td>:<%=@user.name%></td>
  </tr>
  <tr>     
     <td>User Age</td><td>:<%=@user.age%></td>
   </tr></br>
   <tr>
      <td><%=link_to :Edit , edit_user_path(@user, :param1 => "show")%></td>
      <td><%=link_to :Destroy , user_path(@user) , :method=>:delete , :confirm=>"r u sure"%></td>
   </tr>
   <tr colspan='2'>
   <td><%=link_to :Index ,users_index_path%></td>   
  </tr>
</table>


    